// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"gorm.io/gorm"
	"online-course/internal/product/delivery/http"
	"online-course/internal/product/repository"
	product2 "online-course/internal/product/usecase"
	"online-course/pkg/file/cloudinary"
)

// Injectors from wire.go:

func InitiliazeService(db *gorm.DB) *product.ProductHandler {
	productRepository := repository.NewProductRepository(db)
	file := image.NewFile()
	productUseCase := product2.NewProductUseCase(productRepository, file)
	productHandler := product.NewProductHandler(productUseCase)
	return productHandler
}
